// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cloudscribe.Kvp.Storage.EFCore.PostgreSql;

namespace cloudscribe.Kvp.Storage.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(KvpDbContext))]
    [Migration("20181008180223_cs-kvp-initial")]
    partial class cskvpinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("cloudscribe.Kvp.Models.KvpItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasMaxLength(36);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnName("created_utc");

                    b.Property<string>("Custom1")
                        .HasColumnName("custom1")
                        .HasMaxLength(255);

                    b.Property<string>("Custom2")
                        .HasColumnName("custom2")
                        .HasMaxLength(255);

                    b.Property<string>("FeatureId")
                        .HasColumnName("feature_id")
                        .HasMaxLength(36);

                    b.Property<string>("Key")
                        .HasColumnName("key")
                        .HasMaxLength(255);

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnName("modified_utc");

                    b.Property<string>("SetId")
                        .HasColumnName("set_id")
                        .HasMaxLength(36);

                    b.Property<string>("SubSetId")
                        .HasColumnName("sub_set_id")
                        .HasMaxLength(36);

                    b.Property<string>("Value")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kvp_items");

                    b.HasIndex("FeatureId")
                        .HasName("ix_kvp_items_feature_id");

                    b.HasIndex("Key")
                        .HasName("ix_kvp_items_key");

                    b.HasIndex("SetId")
                        .HasName("ix_kvp_items_set_id");

                    b.HasIndex("SubSetId")
                        .HasName("ix_kvp_items_sub_set_id");

                    b.ToTable("kvp_items");
                });
#pragma warning restore 612, 618
        }
    }
}
