// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cloudscribe.Kvp.Storage.EFCore.PostgreSql;

#nullable disable

namespace cloudscribe.Kvp.Storage.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(KvpDbContext))]
    [Migration("20221031101240_cs-kvp-timestamps")]
    partial class cskvptimestamps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cloudscribe.Kvp.Models.KvpItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Custom1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom1");

                    b.Property<string>("Custom2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom2");

                    b.Property<string>("FeatureId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("feature_id");

                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("SetId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("set_id");

                    b.Property<string>("SubSetId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sub_set_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kvp_items");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("ix_kvp_items_feature_id");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_kvp_items_key");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_kvp_items_set_id");

                    b.HasIndex("SubSetId")
                        .HasDatabaseName("ix_kvp_items_sub_set_id");

                    b.ToTable("kvp_items");
                });
#pragma warning restore 612, 618
        }
    }
}
